apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: demo-pod-local:latest
        imagePullPolicy: Never  # <== penting agar ambil dari lokal
        ports:
        - containerPort: 3000
