apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nginx-cluster-rogers
  region: ap-southeast-3

managedNodeGroups:
  - name: nginx-ng-rogers
    instanceTypes:
      - t3.micro
      - t3.small
    minSize: 3
    maxSize: 6
    desiredCapacity: 4
    spot: true