apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core-service
        image: core-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "core-service"
